### ISSUE TITLE
Updating offsets?

### ISSUE THREAD

**Issue by Wearwolfy** [lil-skies/MODERN-WARFARE-SOURCE#1]
Do you have a tool for fetching offsets? I am using a decryption tool but it's outdated, are the sig's still viable?

**Comment by lil-skies** [comment]
> Do you have a tool for fetching offsets? I am using a decryption tool but it's outdated, are the sig's still viable?

I’ll update the signatures and push it to the Git. But yes, most of these signatures are still valid, I’ll double check them though.

**Comment by Wearwolfy** [comment]
Thanks alot I appreciate it

**Comment by lil-skies** [comment]
> Thanks alot I appreciate it

Updated.
